### ISSUE TITLE
Add RSA-SHA1 Signer to support JIRA, XERO Private

### ISSUE THREAD

**Issue by dghubble** [dghubble/oauth1#5]
* http://developer.xero.com/documentation/getting-started/private-applications/
* https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-oauth-authentication

**Comment by shamiq** [comment]
@dghubble thoughts on where to get started?

### Option 1
If we change config to include fields for a *rsa.PrivateKey and a signer interface, we can then change the oauth1.Signer to oauth1.HMACSigner, implementing the new signer interface. This allows us to add an oauth1.RSASigner. NewConfig can now verify the secret is set for HMAC, and a key is provided for RSA. 
#### Pros
- Allows for other, future, custom signature methods (RFC 5849 3.4)

#### Cons
- changes the user API.

### Option 2
Extend oauth1.Config to include a *rsa.PrivateKey. Add checks in signer for this key. If set use RSA, else HMAC. Roll RSA signature code into existing signer.

#### Pros
- Shouldn't break existing user API

#### Cons
- Hacky.

**Comment by dghubble** [comment]
I've intended to make `oauth1.Signer` an interface and do some restructuring to support new signature methods. I favor making some breaks over introducing hacks for RSA signing for JIRA. But changes can't break upstream users of https://github.com/dghubble/gologin who create `oauth1.Config` objects so an HMAC Signer have to be treated as the Config's default. I need to revisit this and the spec on a free weekend soon.

Are you primarily interested in JIRA support? Or just in client spec completeness?

**Comment by shamiq** [comment]
100% for JIRA support. I plan to use it with [go-jira](https://github.com/andygrunwald/go-jira) for creating issues via API.  

In gologin, I see the usage subsection suggesting to use `&Config{}` to create config objects rather than `NewConfig()` -- does this mean we can change the function signature for `NewConfig`, and then recommend `NewConfig` be used going forwards?

Since my need for JIRA+OAuth1 is now, I'm just going to privately fork out and make a hacky change to SetRequestTokenAuthHeader, SetAccessTokenAuthHeader, and Config to include a new pkey, if branch on !=nil for the pkey, and then call a signatureRSA method. Lmk when you've looked at it, and we can patch things up nicely.
